// Set the upper bound
let upperBound = 6

// Set the lower bound
let lowerBound = 1

// Random number logic - Multiply the number generated by 
// the random() function by the length of range
// and then add the lower bound
let randomNumber = Math.floor(Math.random() * (upperBound - lowerBound + 1)) + lowerBound

// Print the result(randomNumber)
console.log(randomNumber);
